seed: 0

imitation:
  num_epochs: 60
  iterations_per_batch: 10
  patience: 10
  min_delta: 0.01

env:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 4
    init_position_noise_level: 0
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

env_0:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 4
    init_position_noise_level: 0
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

env_1:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 4
    init_position_noise_level: 0
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

env_2:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 4
    init_position_noise_level: 0.15
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

env_3:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 4
    init_position_noise_level: 0.2
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

env_4:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 4
    init_position_noise_level: 0.25
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

env_5:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 4
    init_position_noise_level: 0.3
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

env_6:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 4
    init_position_noise_level: 0.35
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

env_7:
  max_steps: 200
  scenario_name: "formation_control"
  scenario:
    n_agents: 2
    init_position_noise_level: 0.4
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

model:
  shared_parameters: True
  centralised_critic: True  # MAPPO if True, IPPO if False

collector:
  frames_per_batch: 18000 # Frames sampled each sampling iteration
  n_iters: 2000 # Number of sampling/training iterations
  total_frames: 36000

buffer:
  memory_size: ???

loss:
  gamma: 0.9
  lmbda: 0.9
  entropy_eps: 0.01
  clip_epsilon: 0.2

train:
  num_epochs: 10 # optimization steps per batch of data collected
  minibatch_size: 4096 # size of minibatches used in each epoch
  lr: 5e-5
  max_grad_norm: 40.0
  device: ???

eval:
  evaluation_interval: 5
  evaluation_episodes: 200
  checkpoint_path: "/home/ysc/multi_formation/multiagent/outputs/2024-05-29/13-54-10/test_policy_120.pth"

logger:
  # backend : null
  backend: wandb # Delete to remove logging
  project_name: null
  group_name: null
